version: 0.2

run-as: root

env:
  parameter-store:
    a: "/pankaj/mongo-url"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing...
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
  build:
    commands:
      - sed -i "s|localhost|"$MongoDb_url"|" app.js
      - echo Building ...

  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - '**/*'
    - echo Uploaded Artifacts
